import Head from 'next/head';
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { About } from '../components/About';
import { Project } from '../components/Project';
import { useTheme } from "next-themes";
import { Skills } from '../components/Skills';
import { Contact } from '../components/Contact';
import { Footer } from '../components/Footer';
import { Client } from '../lib/client';



export default function Home({ aboutData, projectData, skillData, experiencesData, cvData, logoData }) {
  const { theme, setTheme } = useTheme();
  return (
    <div className='max-w-full lg:max-w-7xl lg:mx-auto'>
      <Head>
        <title>Salman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/salman-head-logo.png" />
      </Head>

      <Navbar theme={theme} setTheme={setTheme} logo={logoData.length && logoData[0]} />
      <Hero theme={theme} cv={cvData.length && cvData[0]} />
      <About about={aboutData.length && aboutData[0]} />
      <Project project={projectData} />
      <Skills skills={skillData} experiences={experiencesData} />
      <Contact />
      <Footer />

    </div>
  )
}


export const getServerSideProps = async () => {
  const aboutQuery = `*[_type == "abouts"]`;
  const aboutData = await Client.fetch(aboutQuery);

  const projectQuery = `*[_type == "projects"]`;
  const projectData = await Client.fetch(projectQuery);

  const skillQuery = `*[_type == "skills"]`;
  const skillData = await Client.fetch(skillQuery);

  const experiencesQuery = `*[_type == "experiences"]`;
  const experiencesData = await Client.fetch(experiencesQuery);

  const logoQuery = `*[_type == "logo"]`;
  const logoData = await Client.fetch(logoQuery);

  const cvQuery = `*[_type == "cv"] {
    mycv,
    "cvURL": mycv.asset->url
  }`;
  const cvData = await Client.fetch(cvQuery);

  return {
    props: { aboutData, projectData, skillData, experiencesData, cvData, logoData }
  }
}


