import Head from 'next/head';
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { About } from '../components/About';
import { Project } from '../components/Project';
import { useTheme } from "next-themes";
import { Skills } from '../components/Skills';
import { Contact } from '../components/Contact';
import { Footer } from '../components/Footer';
import { Client } from '../lib/client';
// import styles from '../styles/Home.module.css';


export default function Home({ aboutData, projectData, skillData, experiencesData, cvData }) {
  const { theme, setTheme } = useTheme();
  return (
    <div className='max-w-full lg:max-w-7xl lg:mx-auto'/* max-w-full px-[8%] max-w-7xl mx-auto  max-w-full px-[8%] lg:max-w-7xl lg:mx-auto */>
      <Head>
        <title>Salman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/salman-head-logo.png" />
      </Head>

      <Navbar theme={theme} setTheme={setTheme} />
      <Hero theme={theme} cv={cvData.length && cvData[0]} />
      <About about={aboutData.length && aboutData[0]} />
      <Project project={projectData} />
      <Skills skills={skillData} experiences={experiencesData} />
      <Contact />
      <Footer />

      {/* <main className='flex justify-between items-center'>
        <img src="images/salman1.png" className='rounded-full object-contain cursor-pointer' alt="Salman" width="50" height="" />
        <nav className='flex items-center space-x-10'>
          <ul><a href="#">Home</a></ul>
          <ul><a href="#">Contact Me</a></ul>
          <ul><a href="#">Skill</a></ul>
          <ul><a href="#">Project</a></ul>
          <ul><a href="#">About Me</a></ul>
        </nav>
      </main> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}


export const getServerSideProps = async () => {
  const aboutQuery = `*[_type == "abouts"]`;
  const aboutData = await Client.fetch(aboutQuery);

  const projectQuery = `*[_type == "projects"]`;
  const projectData = await Client.fetch(projectQuery);

  const skillQuery = `*[_type == "skills"]`;
  const skillData = await Client.fetch(skillQuery);

  const experiencesQuery = `*[_type == "experiences"]`;
  const experiencesData = await Client.fetch(experiencesQuery);

  const cvQuery = `*[_type == "cv"] {
    mycv,
    "cvURL": mycv.asset->url
  }`;
  const cvData = await Client.fetch(cvQuery);

  return {
    props: { aboutData, projectData, skillData, experiencesData, cvData }
  }
}